config:
  use_colors: True

local:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: ehannon
      pass: ''
      dbname: ehannon
      schema: pokemon_analysis
